apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgresql-dumps-container
  labels:
    app: postgresql-dumper
spec:
  serviceName: postgresql-dumper-service
  replicas: 2
  selector:
    matchLabels:
      app: postgresql-dumper
  template:
    metadata:
      name: postgresql-dump-replica
      labels:
        app: postgresql-dumper
    spec:
      containers:
      - name: postgresql-dump-container
        image: shakalyan/dumps-pod:0.1
        command: ["/bin/sh", "-c"]
        args: ["service ssh start; tail -f /dev/null"]
        volumeMounts:
          - name: dumps
            mountPath: /dumps
        imagePullPolicy: Always
  volumeClaimTemplates:
  - metadata:
      name: dumps
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 3Gi