apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongos-deployment
  labels:
    app: mongos
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongos
  template:
    metadata:
      name: mongos-replica
      labels:
        app: mongos
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: mongodb
        image: shakalyan/sns_mongo:0.1
        env:
        - name: MONGO_INITDB_DATABASE
          value: "sns_online_store"
        - name: MONGO_INITDB_ROOT_USERNAME
          valueFrom:
            secretKeyRef:
              name: mongo-secrets
              key: username
        - name: MONGO_INITDB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mongo-secrets
              key: password
        command: ["/bin/sh"]
        args: ["-c", "mongos --bind_ip_all --configdb ConfigRS/mongo-configdb-statefulset-0.mongo-configdb-service:27019"]
        ports:
        - containerPort: 27017
