apiVersion: v1
kind: Service
metadata:
  name: app-service
  labels:
    app: sns_online_store
spec:
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
  selector:
    app: sns_online_store