apiVersion: v1
kind: Service
metadata:
  name: mongo-shard2-service
  labels:
    app: mongo-shard2
spec:
  type: ClusterIP
  clusterIP: None
  ports:
  - port: 27018
    targetPort: 27018
    protocol: TCP
  selector:
    app: mongo-shard2