apiVersion: v1
kind: Service
metadata:
  name: mongo-configdb-service
  labels:
    app: mongo-configdb
spec:
  type: ClusterIP
  clusterIP: None
  ports:
  - port: 27019
    targetPort: 27019
    protocol: TCP
  selector:
    app: mongo-configdb