apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongo-shard2-statefulset
  labels:
    app: mongo-shard2
spec:
  serviceName: mongo-shard2-service
  replicas: 1
  selector:
    matchLabels:
      app: mongo-shard2
  template:
    metadata:
      name: mongo-shard2-replica
      labels:
        app: mongo-shard2
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: mongodb
        image: mongo:6.0.5
        env:
        - name: MONGO_INITDB_DATABASE
          value: "sns_online_store"
        - name: MONGO_INITDB_ROOT_USERNAME
          valueFrom:
            secretKeyRef:
              name: mongo-secrets
              key: username
        - name: MONGO_INITDB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mongo-secrets
              key: password
        command: ["/bin/sh"]
        args: ["-c", "mongod --replSet=Shard2RS --bind_ip_all --shardsvr --port 27018"]
        ports:
        - containerPort: 27018
        volumeMounts:
        - name: mongo-data
          mountPath: /data/db
  volumeClaimTemplates:
  - metadata:
      name: mongo-data
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 3Gi
